const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const port = 8765;
const generated = path.join(root, 'js/generation/generated-data.js');
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json',
  '.webp': 'image/webp', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.woff2': 'font/woff2', '.ogg': 'audio/ogg' };
const validStore = input => input && typeof input === 'object' &&
  ['changed', 'created', 'deleted'].every(key => Array.isArray(input[key]));
http.createServer((req, res) => {
  if (req.method === 'POST' && req.url === '/__save-generation') {
    if (req.headers.origin !== `http://127.0.0.1:${port}`) { res.writeHead(403).end('Forbidden'); return; }
    let body = '';
    req.on('data', chunk => { body += chunk; if (body.length > 4_000_000) req.destroy(); });
    req.on('end', () => {
      try {
        const value = JSON.parse(body);
        if (!validStore(value.sections) || !validStore(value.plans)) throw Error('Invalid generator data');
        fs.writeFileSync(generated, `// Generated by the local section editor.\nwindow.SlimeGeneratedData = ${JSON.stringify(value)};\n`);
        res.writeHead(200, { 'Content-Type': 'application/json' }).end('{"saved":true}');
      } catch (error) { res.writeHead(400).end(String(error.message)); }
    });
    return;
  }
  if (req.method !== 'GET' && req.method !== 'HEAD') { res.writeHead(405).end(); return; }
  const pathname = decodeURIComponent(new URL(req.url, `http://127.0.0.1:${port}`).pathname);
  const file = path.resolve(root, `.${pathname === '/' ? '/index.html' : pathname}`);
  if (file !== root && !file.startsWith(root + path.sep)) { res.writeHead(403).end(); return; }
  if (pathname.split('/').some(part => part.startsWith('.')) || !Object.hasOwn(mime, path.extname(file).toLowerCase())) {
    res.writeHead(403).end(); return;
  }
  fs.stat(file, (error, stat) => {
    if (error || !stat.isFile()) { res.writeHead(404).end(); return; }
    res.writeHead(200, { 'Content-Type': `${mime[path.extname(file).toLowerCase()] || 'application/octet-stream'}; charset=utf-8`,
      'Cache-Control': 'no-store' });
    if (req.method === 'HEAD') res.end(); else fs.createReadStream(file).pipe(res);
  });
}).listen(port, '127.0.0.1', () => console.log(`Generation editor: http://127.0.0.1:${port}/tools/generation/index.html`));
