// Runtime closure used by both the loading screen and Yandex archive builder.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const html = read('index.html');
const pageFiles = new Set(['index.html']);
for (const match of html.matchAll(/(?:src|href)="([^"?#]+)(?:[^"\s]*)"/g)) {
  const file = match[1];
  if (/\.(js|css)$/.test(file) && !file.startsWith('/') && !file.startsWith('data:')) pageFiles.add(file);
}
const context = { window: {} };
for (const file of ['js/config/image-paths.js', 'food-catalog.js', 'world-catalog.js', 'js/config/game-config.js']) vm.runInNewContext(read(file), context);
const resolve = source => context.window.SlimeAssetPaths.resolve(source).split(/[?#]/)[0];
const sources = [...pageFiles].filter(p => !/image-paths|boot-manifest/.test(p)).map(read).join('\n');
const explicit = new Set(context.window.SLIME_FOOD_CATALOG.map(f => resolve(f.image)));
for (const world of context.window.SlimeWorldCatalog.defaults().worlds) {
  for (const block of world.blocks) if (block.image) explicit.add(resolve(block.image));
  for (const name of context.window.SlimeGameConfig.WORLD_SPRITE_NAMES[world.id] || []) explicit.add(resolve(context.window.SlimeWorldCatalog.assetSource(world.id, name) || `assets/world${world.id}/${name}.webp`));
}
const walk = dir => fs.readdirSync(path.join(root, dir), {withFileTypes:true}).flatMap(e => e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
const files = [...walk('assets'), ...walk('effects-lab/assets')];
const dynamicFolders = ['assets/audio/', 'assets/backgrounds/', 'assets/collectibles/flasks/', 'assets/ui/world-icons/', 'assets/ui/portals/', 'assets/ui/icons/', 'assets/ui/combo/', 'assets/vfx/geyser-compact/', 'assets/world2/', 'assets/world3/', 'assets/world4/'];
const included = files.filter(file => {
  if (resolve(file) !== file) return false; // Keep only the current runtime variant.
  const name = path.posix.basename(file), stem = name.replace(/\.[^.]+$/, '');
  return explicit.has(file) || sources.includes(file) || sources.includes(name)
    || sources.includes(`'${stem}'`) || dynamicFolders.some(dir => file.startsWith(dir));
});
for (const file of explicit) if (!fs.existsSync(path.join(root, file))) throw new Error(`Missing catalog asset: ${file}`);
const assets = included.map(file => ({url:file, bytes:fs.statSync(path.join(root, file)).size}));
const revision = context.window.SlimeGameConfig.ASSET_REVISION;
if (process.argv.includes('--write')) {
  fs.writeFileSync(path.join(root, 'js/core/boot-manifest.js'), `// Generated by tools/runtime_inventory.cjs; excludes source artwork and drafts.\nwindow.SlimeBootManifest = ${JSON.stringify({revision, assets})};\n`);
}
process.stdout.write(JSON.stringify({pageFiles:[...pageFiles], assets, revision}));
